/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 raw_assets\Scene_4_Fall.glb -T -j -M 
Files: raw_assets\Scene_4_Fall.glb [2.05MB] > C:\Users\andre\My Stuff\VS Code Projects\tutorials\aimees-papercraft-portfolio\Scene_4_Fall-transformed.glb [133.52KB] (93%)
*/

import { useKTX2Texture } from "../utils/ktxLoader";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { AnimateMesh } from "../components/AnimateMesh";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/Scene_4_Fall-transformed.glb");

  const texture_1 = useKTX2Texture("/textures/Scene_4_Fall_1.webp");
  const texture_2 = useKTX2Texture("/textures/Scene_4_Fall_2.webp");
  const texture_3 = useKTX2Texture("/textures/Scene_4_Fall_3.webp");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Scene_4_Fall_1_Baked.geometry}
        material={texture_1}
        position={nodes.Scene_4_Fall_1_Baked.position}
      />
      <mesh
        geometry={nodes.Scene_4_Fall_2_Baked.geometry}
        material={texture_2}
        position={nodes.Scene_4_Fall_2_Baked.position}
      />

      <AnimateMesh
        axis={"z"}
        offset={0.3}
        amplitude={0.9}
        speed={3}
        position={nodes.Scene_4_Fall_2_Left_Arm.position}
      >
        <mesh
          geometry={nodes.Scene_4_Fall_2_Left_Arm.geometry}
          material={texture_2}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"z"}
        offset={0.3}
        amplitude={0.9}
        speed={3}
        position={nodes.Scene_4_Fall_2_Right_Arm.position}
      >
        <mesh
          geometry={nodes.Scene_4_Fall_2_Right_Arm.geometry}
          material={texture_2}
        />
      </AnimateMesh>

      {/* <AnimateMesh
        axis={"y"}
        offset={0.3}
        amplitude={0.3}
        speed={1.2}
        base={1}
        property={"scale"}
        position={nodes.Scene_4_Fall_2_Fire.position}
      >
        <mesh
          geometry={nodes.Scene_4_Fall_2_Fire.geometry}
          material={texture_2}
        />
      </AnimateMesh> */}
      <AnimateMesh
        axis={"y"}
        offset={0.3}
        amplitude={0.06}
        speed={5}
        base={1}
        property={"scale"}
        position={nodes.Scene_4_Fall_2_Baked_guoba.position}
      >
        <mesh
          geometry={nodes.Scene_4_Fall_2_Baked_guoba.geometry}
          material={texture_2}
        />
      </AnimateMesh>

      <mesh
        geometry={nodes.Scene_4_Fall_3_Baked.geometry}
        material={texture_3}
        position={nodes.Scene_4_Fall_3_Baked.position}
      />
      <AnimateMesh
        axis={"z"}
        offset={0.3}
        amplitude={0.3}
        speed={1.2}
        position={nodes.Scene_4_Fall_3_Cat_Head.position}
      >
        <mesh
          geometry={nodes.Scene_4_Fall_3_Cat_Head.geometry}
          material={texture_3}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"z"}
        offset={0.3}
        amplitude={0.3}
        speed={1.2}
        position={nodes.Scene_4_Fall_3_Bakedbunnyhead001.position}
      >
        <mesh
          geometry={nodes.Scene_4_Fall_3_Bakedbunnyhead001.geometry}
          material={texture_3}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"z"}
        offset={1.3}
        amplitude={0.3}
        speed={1.2}
        position={nodes.Scene_4_Fall_3_Bakedbunnyhead.position}
      >
        <mesh
          geometry={nodes.Scene_4_Fall_3_Bakedbunnyhead.geometry}
          material={texture_3}
        />
      </AnimateMesh>

      <mesh
        geometry={nodes.Scene_4_Fall_3_Baked002.geometry}
        material={texture_3}
        position={nodes.Scene_4_Fall_3_Baked002.position}
      />
      <mesh
        geometry={nodes.Scene_4_Fall_3_Baked003.geometry}
        material={texture_3}
        position={nodes.Scene_4_Fall_3_Baked003.position}
      />
      <mesh
        geometry={nodes.Scene_4_Fall_3_Baked004.geometry}
        material={texture_3}
        position={nodes.Scene_4_Fall_3_Baked004.position}
      />
      <mesh
        geometry={nodes.Scene_4_Fall_3_Baked_spider.geometry}
        material={texture_3}
        position={nodes.Scene_4_Fall_3_Baked_spider.position}
      />
    </group>
  );
}

useGLTF.preload("/models/Scene_4_Fall-transformed.glb");
